apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aiml-sentiment-reviews.name" . }}
  labels:
    {{- include "aiml-sentiment-reviews.labels" . | nindent 4 }}
type: "Opaque"
stringData:
  TRANSFORMERS_CACHE: /app/cache
  G_THREADS: "{{ .Values.gunicorn.threads }}"
  G_TIMEOUT: "{{ .Values.gunicorn.timeout }}"
  reviews_sentiment_sink: {{ .Values.kafkaSink.sentiment }}
  ce_type: {{ .Values.cloudEvents.type }}
  ce_source: {{ .Values.cloudEvents.source }}
