{{- if ne .Values.scope.namespace true -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "streams-console.labels" . | nindent 4 }}
  name: {{ include "streams-console.name" . }}-crb-{{ .Values.user }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "streams-console.name" . }}-cr-{{ .Values.user }}
subjects:
  - kind: ServiceAccount
    name: {{ include "streams-console.name" . }}
    {{- if .Values.namespace }}
    namespace: {{ .Values.namespace }}
    {{- else }}
    namespace: {{ .Release.Namespace }}
    {{- end }}
{{- end }}