apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kafka-connect.name" . }}-hook
  labels:
    {{- include "kafka-connect.labels" . | nindent 4 }}
  annotations: 
    {{- if .Values.hook.argocd.enabled }}
    {{- include "kafka-connect-hook.argocd-syncwave" . | nindent 4 }}
    {{- else }}
    "helm.sh/hook": post-install
    {{- end }}    
spec:
  selector: {}
  template:
    metadata:
      name: {{ include "kafka-connect.name" . }}-hook
    spec:
      serviceAccountName: {{ include "kafka-connect.name" . }}-hook
      securityContext:
        {{- toYaml .Values.hook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.hook.securityContext | nindent 12 }}
          image: "{{ .Values.hook.image.repository }}:{{ .Values.hook.image.tag }}"
          imagePullPolicy: {{ .Values.hook.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KAFKA_CONNECTION_SECRET
              value: {{ include "kafka.client-connection-secret.name" . }}
            - name: KAFKA_CONNECT_NAME
              value: {{ include "kafka-connect.name" . }}            
      restartPolicy: Never