{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rocketchat.serviceAccountName" . }}
  labels:
    {{- include "rocketchat.labels" . | nindent 4 }}
{{- end }}
