kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "networkpolicy.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "networkpolicy.labels" . | nindent 4 }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}