{{- if .Values.kafka.enabled -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "kafka-broker.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
  annotations:
    {{- include "kafka-broker.argocd-syncwave" . | nindent 4 }}
spec:
  kafka:
    replicas: {{ .Values.kafka.cluster.replicas }}
    version: {{ .Values.kafka.version }}
    {{- if eq .Values.authorization "simple" }}
    authorization:
      type: simple
    {{- end }}
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
      {{- include "kafka-broker.authentication" . | nindent 6 }}
    - name: tls
      port: 9093
      type: internal
      tls: true
      {{- include "kafka-broker.authentication" . | nindent 6 }}
    config:
      auto.create.topics.enable: {{ .Values.kafka.config.autoCreateTopics }}
      offsets.topic.replication.factor: {{ .Values.kafka.config.offsetsTopicReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.kafka.config.transactionStateLogMinIsr }}
      transaction.state.log.replication.factor: {{ .Values.kafka.config.transactionStateLogReplicationFactor }}
      default.replication.factor: {{ .Values.kafka.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.kafka.config.minInsyncReplicas }}
      inter.broker.protocol.version: '{{ .Values.kafka.config.interBrokerProtocolVersion }}'
    storage:
      type: ephemeral
    resources:
      {{- toYaml .Values.kafka.resources | nindent 6 }}
  zookeeper:
    replicas: {{ .Values.kafka.zookeeper.replicas }}
    storage:
      type: ephemeral
    resources:
      {{- toYaml .Values.kafka.zookeeper.resources | nindent 6 }}
  entityOperator:
    topicOperator:
      resources:
        {{- toYaml .Values.kafka.entityOperator.topicOperator.resources | nindent 8 }}
    userOperator:
      resources:
        {{- toYaml .Values.kafka.entityOperator.userOperator.resources | nindent 8 }}
{{- end }}
