{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "inventory-db.serviceAccountName" . }}
  labels:
    {{- include "inventory-db.labels" . | nindent 4 }}
{{- end }}
