nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: registry.redhat.io/rhel8/postgresql-12
  pullPolicy: IfNotPresent
  tag: "1"

podSecurityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podAnnotations: {}

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  tcpSocket:
    port: 5432

readinessProbe:
  timeoutSeconds: 1
  initialDelaySeconds: 5
  exec:
    command:
    - "/bin/sh"
    - "-i"
    - "-c"
    - psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d $POSTGRESQL_DATABASE -c 'SELECT 1'

service:
  portName: postgresql
  port: 5432
  containerPort: 5432

serviceAccount:
  create: true
  annotations: {}
  name: ""

pgsql:
  user: keycloak
  password: keycloak
  database: keycloak

persistence:
  mode: persistent
  capacity: 5Gi

argocd:
  enabled: true
  syncwave: "-3"
